upload_project_to_s3:
  image:
    # Esta imagen tiene instalada el CLI de AWS
    # Gracias a esto, puedes correr comandos de AWS CLI desde el pipeline
    name: banst/awscli
    entrypoint: [""]
  script:
    # Setea la región
    - aws configure set region $AWS_DEFAULT_REGION

    # Usando AWS CLI, sube el contenido de la carpeta “code” a tu bucket
    - aws s3 cp $CI_PROJECT_DIR/content/ s3://$AWS_S3_BUCKET_NAME/ --recursive
