version: "3.3"
networks:
  my-app-net:
    name: my-app-net
services:
  myapp:
    image: myapp-node
    working_dir: /myapp
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - my-app-net
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - 8383:6379
    networks:
      - my-app-net 
